# basic workflow that creates secrets

name: Set Action Secret

on: ["push"]
jobs:
  secret:
    runs-on: "ubuntu-latest"
    steps:
    - uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MY_SECRET_NAME'
        value: 'Lorem ipsun dolor simit'
        repository: ${{ github.repository }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
