# basic workflow that creates secrets

name: Secret Bot

on: ["push"]
jobs:
  secret_job:
    runs-on: "ubuntu-latest"
    steps:
      - uses: gliech/create-github-secret-action@v1
        with:
          name: TEST_SECRET
          value: Placeholder
          pa_token: ${{ secrets.PA_TOKEN }}
